In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
nav = webdriver.Chrome()

#Passo 1: Pegar a Cotação do Dólar
#entrar no google
nav.get('https://www.google.com/webhp?hl=en&sa=X&ved=0ahUKEwj7tMPg0cL8AhXkLLkGHQx5CqgQPAgI')
nav.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('cotação dólar')

nav.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

cotacao_dolar = nav.find_element(By.XPATH, '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cotacao_dolar)

#Passo 2: Pegar a Cotação do Euro
nav.get("https://www.google.com/")
nav.find_element(By.XPATH,
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação euro")
nav.find_element(By.XPATH,
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

cotacao_euro = nav.find_element(By.XPATH,
    '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value")
print(cotacao_euro)

#Passo 3: Pegar a Cotação do Ouro
nav.get('https://www.melhorcambio.com/ouro-hoje')

#captura do atributo 'value'(valor) do elemento
cotacao_ouro = nav.find_element(By.XPATH, '//*[@id="comercial"]').get_attribute('value')
cotacao_ouro = cotacao_ouro.replace(',', '.')
print(cotacao_ouro)

nav.quit()

#Passo 5: Recalcular os preços
#Passo 6: Exportar a base atualizada

5.1475
5.574613812
317.93

In [2]:
#Passo 4: Atualizar a base

#etapa 1: Importar Tabela
import pandas as pd
tabela = pd.read_excel('Produtos.xlsx')
display(tabela)

#etapa 2: Atualizando tabela c/ o método loc
tabela.loc[tabela['Moeda'] == 'Dólar', 'Cotação'] = float(cotacao_dolar)
tabela.loc[tabela['Moeda'] == 'Euro', 'Cotação'] = float(cotacao_euro)
tabela.loc[tabela['Moeda'] == 'Ouro', 'Cotação'] = float(cotacao_ouro)

#etapa 3: Recalculando preços de venda 
tabela['Preço de Compra'] = tabela['Preço Original'] = tabela['']
display(tabela)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

KeyError: ''

In [ ]:
!pip install selenium